micronaut:
  application:
    name: keymanagerRest
  server:
    netty:
      access-logger:
        enabled: true

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: ${KEYMANAGER_HOST:localhost}:${KEYMANAGER_PORT:50051}
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false
