apiVersion: v1
kind: Service
metadata:
  name: svc-keymanager-rest
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    api: keymanager-rest
  ports:
    - name: api-server
      port: 8080
      protocol: TCP
    - name: management-server
      port: 8084
      protocol: TCP